USE [covid_19_hosp_usa]
GO

/****** Object:  Table [dbo].[COVID_19_RAW]    Script Date: 1/22/2022 5:52:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COVID_19_RAW](
	[hospital_pk] [varchar](50) NULL,
	[collection_week] [date] NULL,
	[state] [varchar](100) NULL,
	[ccn] [varchar](100) NULL,
	[hospital_name] [nvarchar](100) NULL,
	[address] [varchar](100) NULL,
	[city] [varchar](100) NULL,
	[zip] [varchar](100) NULL,
	[hospital_subtype] [varchar](100) NULL,
	[fips_code] [varchar](100) NULL,
	[is_metro_micro] [varchar](100) NULL,
	[total_beds_7_day_avg] [numeric](18, 0) NULL,
	[all_adult_hospital_beds_7_day_avg] [numeric](18, 0) NULL,
	[all_adult_hospital_inpatient_beds_7_day_avg] [numeric](18, 0) NULL,
	[inpatient_beds_used_7_day_avg] [numeric](18, 0) NULL,
	[all_adult_hospital_inpatient_bed_occupied_7_day_avg] [numeric](18, 0) NULL,
	[inpatient_beds_used_covid_7_day_avg] [numeric](18, 0) NULL,
	[total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg] [numeric](18, 0) NULL,
	[total_adult_patients_hospitalized_confirmed_covid_7_day_avg] [numeric](18, 0) NULL,
	[total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg] [numeric](18, 0) NULL,
	[total_pediatric_patients_hospitalized_confirmed_covid_7_day_avg] [numeric](18, 0) NULL,
	[inpatient_beds_7_day_avg] [numeric](18, 0) NULL,
	[total_icu_beds_7_day_avg] [numeric](18, 0) NULL,
	[total_staffed_adult_icu_beds_7_day_avg] [numeric](18, 0) NULL,
	[icu_beds_used_7_day_avg] [numeric](18, 0) NULL,
	[staffed_adult_icu_bed_occupancy_7_day_avg] [numeric](18, 0) NULL,
	[staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_avg] [numeric](18, 0) NULL,
	[staffed_icu_adult_patients_confirmed_covid_7_day_avg] [numeric](18, 0) NULL,
	[total_patients_hospitalized_confirmed_influenza_7_day_avg] [numeric](18, 0) NULL,
	[icu_patients_confirmed_influenza_7_day_avg] [numeric](18, 0) NULL,
	[total_patients_hospitalized_confirmed_influenza_and_covid_7_day_avg] [numeric](18, 0) NULL,
	[total_beds_7_day_sum] [numeric](18, 0) NULL,
	[all_adult_hospital_beds_7_day_sum] [numeric](18, 0) NULL,
	[all_adult_hospital_inpatient_beds_7_day_sum] [numeric](18, 0) NULL,
	[inpatient_beds_used_7_day_sum] [numeric](18, 0) NULL,
	[all_adult_hospital_inpatient_bed_occupied_7_day_sum] [numeric](18, 0) NULL,
	[inpatient_beds_used_covid_7_day_sum] [numeric](18, 0) NULL,
	[total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum] [numeric](18, 0) NULL,
	[total_adult_patients_hospitalized_confirmed_covid_7_day_sum] [numeric](18, 0) NULL,
	[total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_sum] [numeric](18, 0) NULL,
	[total_pediatric_patients_hospitalized_confirmed_covid_7_day_sum] [numeric](18, 0) NULL,
	[inpatient_beds_7_day_sum] [numeric](18, 0) NULL,
	[total_icu_beds_7_day_sum] [numeric](18, 0) NULL,
	[total_staffed_adult_icu_beds_7_day_sum] [numeric](18, 0) NULL,
	[icu_beds_used_7_day_sum] [numeric](18, 0) NULL,
	[staffed_adult_icu_bed_occupancy_7_day_sum] [numeric](18, 0) NULL,
	[staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_sum] [numeric](18, 0) NULL,
	[staffed_icu_adult_patients_confirmed_covid_7_day_sum] [numeric](18, 0) NULL,
	[total_patients_hospitalized_confirmed_influenza_7_day_sum] [numeric](18, 0) NULL,
	[icu_patients_confirmed_influenza_7_day_sum] [numeric](18, 0) NULL,
	[total_patients_hospitalized_confirmed_influenza_and_covid_7_day_sum] [numeric](18, 0) NULL,
	[total_beds_7_day_coverage] [numeric](18, 0) NULL,
	[all_adult_hospital_beds_7_day_coverage] [numeric](18, 0) NULL,
	[all_adult_hospital_inpatient_beds_7_day_coverage] [numeric](18, 0) NULL,
	[inpatient_beds_used_7_day_coverage] [numeric](18, 0) NULL,
	[all_adult_hospital_inpatient_bed_occupied_7_day_coverage] [numeric](18, 0) NULL,
	[inpatient_beds_used_covid_7_day_coverage] [numeric](18, 0) NULL,
	[total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_coverage] [numeric](18, 0) NULL,
	[total_adult_patients_hospitalized_confirmed_covid_7_day_coverage] [numeric](18, 0) NULL,
	[total_pediatric_patients_hospitalized_confirmed_and_suspected_covid_7_day_coverage] [numeric](18, 0) NULL,
	[total_pediatric_patients_hospitalized_confirmed_covid_7_day_coverage] [numeric](18, 0) NULL,
	[inpatient_beds_7_day_coverage] [numeric](18, 0) NULL,
	[total_icu_beds_7_day_coverage] [numeric](18, 0) NULL,
	[total_staffed_adult_icu_beds_7_day_coverage] [numeric](18, 0) NULL,
	[icu_beds_used_7_day_coverage] [numeric](18, 0) NULL,
	[staffed_adult_icu_bed_occupancy_7_day_coverage] [numeric](18, 0) NULL,
	[staffed_icu_adult_patients_confirmed_and_suspected_covid_7_day_coverage] [numeric](18, 0) NULL,
	[staffed_icu_adult_patients_confirmed_covid_7_day_coverage] [numeric](18, 0) NULL,
	[total_patients_hospitalized_confirmed_influenza_7_day_coverage] [numeric](18, 0) NULL,
	[icu_patients_confirmed_influenza_7_day_coverage] [numeric](18, 0) NULL,
	[total_patients_hospitalized_confirmed_influenza_and_covid_7_day_coverage] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_confirmed_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_confirmed_18-19_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_confirmed_20-29_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_confirmed_30-39_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_confirmed_40-49_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_confirmed_50-59_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_confirmed_60-69_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_confirmed_70-79_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_confirmed_80+_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_confirmed_unknown_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_pediatric_covid_confirmed_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_covid_ED_visits_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_18-19_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_20-29_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_30-39_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_40-49_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_50-59_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_60-69_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_70-79_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_80+_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_unknown_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_pediatric_covid_suspected_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_total_ED_visits_7_day_sum] [numeric](18, 0) NULL,
	[previous_day_admission_influenza_confirmed_7_day_sum] [numeric](18, 0) NULL,
	[geocoded_hospital_address] [varchar](100) NULL,
	[hhs_ids] [varchar](100) NULL,
	[previous_day_admission_adult_covid_confirmed_7_day_coverage] [numeric](18, 0) NULL,
	[previous_day_admission_pediatric_covid_confirmed_7_day_coverage] [numeric](18, 0) NULL,
	[previous_day_admission_adult_covid_suspected_7_day_coverage] [numeric](18, 0) NULL,
	[previous_day_admission_pediatric_covid_suspected_7_day_coverage] [numeric](18, 0) NULL,
	[previous_week_personnel_covid_vaccinated_doses_administered_7_day] [numeric](18, 0) NULL,
	[total_personnel_covid_vaccinated_doses_none_7_day] [numeric](18, 0) NULL,
	[total_personnel_covid_vaccinated_doses_one_7_day] [numeric](18, 0) NULL,
	[total_personnel_covid_vaccinated_doses_all_7_day] [numeric](18, 0) NULL,
	[previous_week_patients_covid_vaccinated_doses_one_7_day] [numeric](18, 0) NULL,
	[previous_week_patients_covid_vaccinated_doses_all_7_day] [numeric](18, 0) NULL
) ON [PRIMARY]
GO


