INSERT INTO dbo.covid_vaccination_data (hospital_pk, collection_week, previous_week_personnel_covid_vaccinated_doses_administered_7_day, previous_week_patients_covid_vaccinated_doses_one_7_day, previous_week_patients_covid_vaccinated_doses_all_7_day, total_personnel_covid_vaccinated_doses_none_7_day, total_personnel_covid_vaccinated_doses_one_7_day, total_personnel_covid_vaccinated_doses_all_7_day)
SELECT hospital_pk, collection_week, previous_week_personnel_covid_vaccinated_doses_administered_7_day, previous_week_patients_covid_vaccinated_doses_one_7_day, previous_week_patients_covid_vaccinated_doses_all_7_day, total_personnel_covid_vaccinated_doses_none_7_day, total_personnel_covid_vaccinated_doses_one_7_day, total_personnel_covid_vaccinated_doses_all_7_day
FROM dbo.COVID_19_RAW


